services:
  prostate_graphs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prostate_graphs
    command: "tail -f /dev/null"
    volumes:
      - /home/esandoval/master/prostate_graphs/:/app/
      - /home/Data/Datasets:/Datasets/
    working_dir: /app
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
